### ISSUE TITLE
bug: can't run on (my) win10

### ISSUE THREAD

**Issue by Gillonz** [MarkWattTech/TuyaKeyExtractor#1]
Hi, thanks for your tool, unfortunately it doesn't work on my pc. I've tried compatibility mode with other versions of windows, but no luck.

**Comment by MarkWattTech** [comment]
Hey! Can you check you have .netcore runtime installed? I have added links to the video descriptions. Install it and give it another go. Cheers.

**Comment by Gillonz** [comment]
Great! Works perfectly, thank you Mark!
